### ISSUE TITLE
CSS colors do not show up in "read" mode

### ISSUE THREAD

**Issue by rajesh-s** [lguenth/obsidian-templates#2]
@lguenth , thanks for the CSS. But this only seems to show colors in the edit mode of obsidian . What change might be necessary for it to show colors in the "read" mode in obsidian as well?

**Comment by lguenth** [comment]
Hey, just following up on this: The colours should work in reading mode – did you figure out what the issue was and therefore resolved this on your end? (Edit: typo)

**Comment by rajesh-s** [comment]
There was some manual css that seemed to override. I disabled all of them and enabled them one at a time to figure out the conflict. Thanks for your work!
